project:
  type: website
  output-dir: docs

website:
  title: "sadiedrucker.github.io"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Data Viz
        menu:
          - text: CDC Datasets
            href: CDCdatasets.qmd
          - text: Water Insecurity
            href: WaterInsecurity.qmd
          - text: New York Times Headlines
            href: NYTHeadlines.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

