---
title: "Mapping Inequality in Los Angeles, California"
format: 
  html:
    code-fold: true
    
execute:
  message: false
  warning: false
---

```{r}
#| echo: false
#| results: 'hide'
#| message: false
#| warning: false
#| cache: TRUE
reticulate::use_miniconda("r-reticulate", required = TRUE)
reticulate::py_config()
reticulate::py_install(c("plotly", "networkx"), envname = "r-reticulate")

```

### Guiding Research Questions

1.  Are neighborhoods segregated by race and/or socioeconomic status?
2.  Is poverty spatially concentrated?
3.  How does public transportation connect different neighborhoods?

### Mathematical Tools

I employed methods such as Graph Theory and Counting to develop a model that could address these research questions.

#### Graph Theory

I aimed to create a graph of neighborhoods in Los Angeles where nodes represented neighborhoods and edges were established between nodes if public transportation between them takes less than thirty minutes. I then overlaid poverty and race data on the graph.

#### Counting

There are 114 officially recognized neighborhoods in Los Angeles.\

If I wanted to keep track of the public transportation travel time between every pair of neighborhoods, I would need to look up the travel time for every possible origin–destination combination.

We consider the set of $V$ of $n$, where $n=114$ neighborhoods

We want to count the number of ordered pairs $(u,v)$ such that:

-   $u \in V$ (origin)

-   $v \in V$ (destination)\\

-   $u \ne v$ (no self loops)

The total number of such pairs is:$=P(114, 2)=\frac{114!}{(114-2)!}=\frac{114!}{112!}=n(n-1)=114*113=12882$

This means there are **12,882** unique direction queries to collect.

Looking up this many connections manually would be impossible in practice.\

Once I recognized the scale of the problem, I designed an automated system using the Google Directions API to generate the full set of travel-time connections programmatically.

```{python}
#| code-fold: true
#| code-summary: "Show code"
#| output: false
# !pip install googlemaps
# !pip install networkx
# import networkx as nx
# import googlemaps
# import time
# from datetime import datetime
# import matplotlib.pyplot as plt
# 
# 
# G=nx.Graph() #creates graph
# for neighborhood in neighborhoods: 
#     G.addnode(neighborhood) #defines nodes 
# 
# 
# gmaps=googlemaps.Client(key=#insert API key here)
# neighborhoods=["Adams-Normandie, Los Angeles", 
# "Arleta, Los Angeles", 
# "Arlington Heights, Los Angeles", 
# "Atwater Village, Los Angeles", 
# "Baldwin Hills/Crenshaw, Los Angeles", 
# "Bel-Air, Los Angeles", 
# "Beverly Crest, Los Angeles", 
# "Beverly Grove, Los Angeles", 
# "Beverlywood, Los Angeles", 
# "Boyle Heights, Los Angeles", 
# "Brentwood, Los Angeles", 
# "Broadway-Manchester, Los Angeles", 
# "Canoga Park, Los Angeles", 
# "Carthay, Los Angeles", 
# "Central-Alameda, Los Angeles", 
# "Century City, Los Angeles", 
# "Chatsworth, Los Angeles", 
# "Chatsworth Reservoir, Los Angeles", 
# "Chesterfield Square, Los Angeles", 
# "Cheviot Hills, Los Angeles", 
# "Chinatown, Los Angeles", 
# "Cypress Park, Los Angeles", 
# "Del Rey, Los Angeles", 
# "Downtown, Los Angeles", 
# "Eagle Rock, Los Angeles", 
# "East Hollywood, Los Angeles", 
# "Echo Park, Los Angeles", 
# "El Sereno, Los Angeles", 
# "Elysian Park, Los Angeles", 
# "Elysian Valley, Los Angeles", 
# "Encino, Los Angeles", 
# "Exposition Park, Los Angeles", 
# "Fairfax, Los Angeles", 
# "Florence, Los Angeles", 
# "Glassell Park, Los Angeles", 
# "Gramercy Park, Los Angeles", 
# "Granada Hills, Los Angeles", 
# "Green Meadows, Los Angeles", 
# "Griffith Park, Los Angeles", 
# "Hancock Park, Los Angeles", 
# "Hansen Dam, Los Angeles", 
# "Harbor City, Los Angeles", 
# "Harbor Gateway, Los Angeles", 
# "Harvard Heights, Los Angeles", 
# "Harvard Park, Los Angeles", 
# "Highland Park, Los Angeles", 
# "Historic South-Central, Los Angeles", 
# "Hollywood Hills, Los Angeles", 
# "Hollywood Hills West, Los Angeles", 
# "Hollywood, Los Angeles", 
# "Hyde Park, Los Angeles", 
# "Jefferson Park, Los Angeles", 
# "Koreatown, Los Angeles", 
# "Lake View Terrace, Los Angeles", 
# "Larchmont, Los Angeles", 
# "Leimert Park, Los Angeles", 
# "Lincoln Heights, Los Angeles", 
# "Los Feliz, Los Angeles", 
# "Manchester Square, Los Angeles", 
# "Mar Vista, Los Angeles", 
# "Mid-City, Los Angeles", 
# "Mid-Wilshire, Los Angeles", 
# "Mission Hills, Los Angeles", 
# "Montecito Heights, Los Angeles", 
# "Mount Washington, Los Angeles", 
# "North Hills, Los Angeles", 
# "North Hollywood, Los Angeles", 
# "Northridge, Los Angeles", 
# "Pacific Palisades, Los Angeles", 
# "Pacoima, Los Angeles", 
# "Palms, Los Angeles", 
# "Panorama City, Los Angeles", 
# "Pico-Robertson, Los Angeles", 
# "Pico-Union, Los Angeles", 
# "Playa del Rey, Los Angeles", 
# "Playa Vista, Los Angeles", 
# "Porter Ranch, Los Angeles", 
# "Rancho Park, Los Angeles", 
# "Reseda, Los Angeles",
# "San Pedro, Los Angeles", 
# "Sawtelle, Los Angeles", 
# "Sepulveda Basin, Los Angeles", 
# "Shadow Hills, Los Angeles", 
# "Sherman Oaks, Los Angeles", 
# "Silver Lake, Los Angeles", 
# "South Park, Los Angeles", 
# "Studio City, Los Angeles", 
# "Sunland, Los Angeles", 
# "Sun Valley, Los Angeles", 
# "Sylmar, Los Angeles", 
# "Tarzana, Los Angeles", 
# "Toluca Lake, Los Angeles", 
# "Tujunga, Los Angeles", 
# "University Park, Los Angeles", 
# "Valley Glen, Los Angeles", 
# "Valley Village, Los Angeles", 
# "Van Nuys, Los Angeles", 
# "Venice, Los Angeles", 
# "Vermont Knolls, Los Angeles", 
# "Vermont-Slauson, Los Angeles", 
# "Vermont Square, Los Angeles", 
# "Vermont Vista, Los Angeles", 
# "Watts, Los Angeles", 
# "West Adams, Los Angeles", 
# "Westchester, Los Angeles", 
# "West Hills, Los Angeles", 
# "Westlake, Los Angeles", 
# "West Los Angeles, Los Angeles", 
# "Westwood, Los Angeles", 
# "Wilmington, Los Angeles", 
# "Windsor Square, Los Angeles", 
# "Winnetka, Los Angeles", 
# "Woodland Hills, Los Angeles", 
# "Lake Balboa, Los Angeles", ]
# 
# origin="Broadway-Manchester, Los Angeles" #starts at arbitrary neighborhood
# 
# 
# now=datetime.now()
# 
# for origin in neighborhoods:
#     for destination in neighborhoods:
#         if destination != origin: #if destination does not equal origin
#             try: 
#                 directions_result = gmaps.directions(origin, destination, mode="transit", departure_time=now) #set googlemaps to public transit mode
#                
#                 
#                 if directions_result:
#                     duration_seconds = directions_result[0]['legs'][0]['duration']['value']
#                     duration_text = directions_result[0]['legs'][0]['duration']['text']
# 
#                     if duration_seconds < 30 * 60: #if duration is less than 30 minutes
#                         print(f"{origin} → {destination}: {duration_text}") #print amount of time, not really neccessary for this project
# 
#                
#                 time.sleep(0.2) #wait between each call to prevent crashing
# 
#             except Exception as e:
#                 print(f"Error with {origin} to {destination}: {e}")
                
```

```{python}
#| code-fold: true
#| code-summary: "Show code"
#| output: false
#| cache: true


import plotly.graph_objects as go
import networkx as nx
import numpy as np

#manually typed in connections
connections=[("Adams-Normandie, Los Angeles", "Arlington Heights, Los Angeles"), 
("Adams-Normandie, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Adams-Normandie, Los Angeles","Chesterfield Square, Los Angeles"), 
("Adams-Normandie, Los Angeles","Exposition Park, Los Angeles"), 
("Adams-Normandie, Los Angeles", "Harvard Heights, Los Angeles"), 
("Adams-Normandie, Los Angeles","Harvard Park, Los Angeles"), 
("Adams-Normandie, Los Angeles", "Jefferson Park, Los Angeles"), 
("Adams-Normandie, Los Angeles", "Koreatown, Los Angeles"), 
("Adams-Normandie, Los Angeles", "Mid-City, Los Angeles"), 
("Adams-Normandie, Los Angeles","Pico-Union, Los Angeles"), 
("Adams-Normandie, Los Angeles", "University Park, Los Angeles"), 
("Adams-Normandie, Los Angeles", "Vermont Square, Los Angeles"),
("Adams-Normandie, Los Angeles", "West Adams, Los Angeles"), 
("Adams-Normandie, Los Angeles", "Westlake, Los Angeles"), 
("Arleta, Los Angeles", "North Hills, Los Angeles"), 
("Arleta, Los Angeles", "Panorama City, Los Angeles"), 
("Arlington Heights, Los Angeles", "Adams-Normandie, Los Angeles"), 
("Arlington Heights, Los Angeles",  "Baldwin Hills/Crenshaw, Los Angeles"), 
("Arlington Heights, Los Angeles",  "Exposition Park, Los Angeles"), 
("Arlington Heights, Los Angeles", "Harvard Heights, Los Angeles"), 
("Arlington Heights, Los Angeles",  "Jefferson Park, Los Angeles"), 
("Arlington Heights, Los Angeles",  "Mid-City, Los Angeles"), 
("Arlington Heights, Los Angeles",  "Mid-Wilshire, Los Angeles"), 
("Arlington Heights, Los Angeles",  "Pico-Union, Los Angeles"), 
("Arlington Heights, Los Angeles",  "University Park, Los Angeles"), 
("Arlington Heights, Los Angeles",  "West Adams, Los Angeles"), 
("Arlington Heights, Los Angeles", "Westlake, Los Angeles"), 
("Atwater Village, Los Angeles",  "Downtown, Los Angeles"), 
("Atwater Village, Los Angeles", "Echo Park, Los Angeles"), 
("Atwater Village, Los Angeles", "Elysian Valley, Los Angeles"), 
("Atwater Village, Los Angeles", "Glassell Park, Los Angeles"), 
("Atwater Village, Los Angeles", "Griffith Park, Los Angeles"), 
("Atwater Village, Los Angeles", "Los Feliz, Los Angeles"), 
("Atwater Village, Los Angeles", "Silver Lake, Los Angeles"), 
("Atwater Village, Los Angeles", "Westlake, Los Angeles"), 
("Baldwin Hills/Crenshaw, Los Angeles", "Arlington Heights, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Chesterfield Square, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Exposition Park, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Hyde Park, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Jefferson Park, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Mid-City, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Palms, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Rancho Park, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Sawtelle, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "Vermont Square, Los Angeles"),
("Baldwin Hills/Crenshaw, Los Angeles", "West Los Angeles, Los Angeles"),
("Beverly Grove, Los Angeles", "Carthay, Los Angeles"),
("Beverly Grove, Los Angeles", "Fairfax, Los Angeles"),
("Beverly Grove, Los Angeles", "Hancock Park, Los Angeles"),
("Beverly Grove, Los Angeles", "Mid-City, Los Angeles"),
("Beverly Grove, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Beverly Grove, Los Angeles", "Pico-Robertson, Los Angeles"),
("Beverly Grove, Los Angeles", "Windsor Square, Los Angeles"),
("Beverly Grove, Los Angeles", "Carthay, Los Angeles"),
("Beverly Grove, Los Angeles", "Century City, Los Angeles"),
("Beverly Grove, Los Angeles", "Pico-Robertson, Los Angeles"),
("Beverly Grove, Los Angeles", "Rancho Park, Los Angeles"),
("Beverly Grove, Los Angeles", "West Los Angeles, Los Angeles"),
("Boyle Heights, Los Angeles", "Cypress Park, Los Angeles"),
("Boyle Heights, Los Angeles", "Downtown, Los Angeles"),
("Boyle Heights, Los Angeles", "El Sereno, Los Angeles"),
("Boyle Heights, Los Angeles", "Lincoln Heights, Los Angeles"),
("Brentwood, Los Angeles", "Westwood, Los Angeles"),
("Broadway-Manchester, Los Angeles", "Florence, Los Angeles"),
("Broadway-Manchester, Los Angeles", "Gramercy Park, Los Angeles"),
("Broadway-Manchester, Los Angeles", "Green Meadows, Los Angeles"),
("Broadway-Manchester, Los Angeles", "South Park, Los Angeles"),
("Broadway-Manchester, Los Angeles", "Vermont Knolls, Los Angeles"),
("Broadway-Manchester, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Broadway-Manchester, Los Angeles", "Vermont Vista, Los Angeles"),
("Broadway-Manchester, Los Angeles", "Watts, Los Angeles"),
("Canoga Park, Los Angeles", "West Hills, Los Angeles"),
("Canoga Park, Los Angeles", "Winnetka, Los Angeles"),
("Carthay, Los Angeles", "Beverly Grove, Los Angeles"),
("Carthay, Los Angeles", "Beverlywood, Los Angeles"),
("Carthay, Los Angeles", "Century City, Los Angeles"),
("Carthay, Los Angeles", "Fairfax, Los Angeles"),
("Carthay, Los Angeles", "Mid-City, Los Angeles"),
("Carthay, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Carthay, Los Angeles", "Pico-Robertson, Los Angeles"),
("Central-Alameda, Los Angeles", "Boyle Heights, Los Angeles"),
("Central-Alameda, Los Angeles", "Historic South-Central, Los Angeles"),
("Central-Alameda, Los Angeles", "South Park, Los Angeles"),
("Central-Alameda, Los Angeles", "Watts, Los Angeles"),
("Century City, Los Angeles", "Beverlywood, Los Angeles"),
("Century City, Los Angeles", "Carthay, Los Angeles"),
("Century City, Los Angeles", "Palms, Los Angeles"),
("Century City, Los Angeles", "Pico-Robertson, Los Angeles"),
("Century City, Los Angeles", "Sawtelle, Los Angeles"),
("Century City, Los Angeles", "West Los Angeles, Los Angeles"),
("Century City, Los Angeles", "Westwood, Los Angeles"),
("Chatsworth, Los Angeles", "Canoga Park, Los Angeles"),
("Chatsworth, Los Angeles", "Winnetka, Los Angeles"),
("Chesterfield Square, Los Angeles", "Gramercy Park, Los Angeles"),
("Chesterfield Square, Los Angeles", "Harvard Park, Los Angeles"),
("Chesterfield Square, Los Angeles", "Hyde Park, Los Angeles"),
("Chesterfield Square, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Chesterfield Square, Los Angeles", "Vermont Square, Los Angeles"),
("Cheviot Hills, Los Angeles", "Palms, Los Angeles"),
("Cheviot Hills, Los Angeles", "Rancho Park, Los Angeles"),
("Cheviot Hills, Los Angeles", "West Los Angeles, Los Angeles"),
("Chinatown, Los Angeles", "Cypress Park, Los Angeles"),
("Chinatown, Los Angeles", "Downtown, Los Angeles"),
("Chinatown, Los Angeles", "Echo Park, Los Angeles"),
("Chinatown, Los Angeles", "El Sereno, Los Angeles"),
("Chinatown, Los Angeles", "Elysian Valley, Los Angeles"),
("Chinatown, Los Angeles", "Glassell Park, Los Angeles"),
("Chinatown, Los Angeles", "Highland Park, Los Angeles"),
("Chinatown, Los Angeles", "Lincoln Heights, Los Angeles"),
("Chinatown, Los Angeles", "Montecito Heights, Los Angeles"),
("Chinatown, Los Angeles", "Silver Lake, Los Angeles"),
("Cypress Park, Los Angeles", "Boyle Heights, Los Angeles"),
("Cypress Park, Los Angeles", "Chinatown, Los Angeles"),
("Cypress Park, Los Angeles", "Eagle Rock, Los Angeles"),
("Cypress Park, Los Angeles", "Elysian Valley, Los Angeles"),
("Cypress Park, Los Angeles", "Glassell Park, Los Angeles"),
("Cypress Park, Los Angeles", "Lincoln Heights, Los Angeles"),
("Cypress Park, Los Angeles", "Montecito Heights, Los Angeles"),
("Del Rey, Los Angeles", "Mar Vista, Los Angeles"),
("Del Rey, Los Angeles", "Playa Vista, Los Angeles"),
("Del Rey, Los Angeles", "Rancho Park, Los Angeles"),
("Del Rey, Los Angeles", "Sawtelle, Los Angeles"),
("Downtown, Los Angeles", "Adams-Normandie, Los Angeles"),
("Downtown, Los Angeles", "Atwater Village, Los Angeles"),
("Downtown, Los Angeles", "Boyle Heights, Los Angeles"),
("Downtown, Los Angeles", "Central-Alameda, Los Angeles"),
("Downtown, Los Angeles", "Chinatown, Los Angeles"),
("Downtown, Los Angeles", "Cypress Park, Los Angeles"),
("Downtown, Los Angeles", "East Hollywood, Los Angeles"),
("Downtown, Los Angeles", "Echo Park, Los Angeles"),
("Downtown, Los Angeles", "El Sereno, Los Angeles"),
("Downtown, Los Angeles", "Exposition Park, Los Angeles"),
("Downtown, Los Angeles", "Koreatown, Los Angeles"),
("Downtown, Los Angeles", "Lincoln Heights, Los Angeles"),
("Downtown, Los Angeles", "Pico-Union, Los Angeles"),
("Downtown, Los Angeles", "Silver Lake, Los Angeles"),
("Downtown, Los Angeles", "University Park, Los Angeles"),
("Downtown, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Downtown, Los Angeles", "West Adams, Los Angeles"),
("Downtown, Los Angeles", "Westlake, Los Angeles"),
("Eagle Rock, Los Angeles", "Cypress Park, Los Angeles"),
("Eagle Rock, Los Angeles", "Glassell Park, Los Angeles"),
("Eagle Rock, Los Angeles", "Highland Park, Los Angeles"),
("East Hollywood, Los Angeles", "Downtown, Los Angeles"),
("East Hollywood, Los Angeles", "Echo Park, Los Angeles"),
("East Hollywood, Los Angeles", "Hancock Park, Los Angeles"),
("East Hollywood, Los Angeles", "Hollywood, Los Angeles"),
("East Hollywood, Los Angeles", "Koreatown, Los Angeles"),
("East Hollywood, Los Angeles", "Larchmont, Los Angeles"),
("East Hollywood, Los Angeles", "Los Feliz, Los Angeles"),
("East Hollywood, Los Angeles", "Silver Lake, Los Angeles"),
("East Hollywood, Los Angeles", "Westlake, Los Angeles"),
("East Hollywood, Los Angeles", "Windsor Square, Los Angeles"),
("Echo Park, Los Angeles", "Atwater Village, Los Angeles"),
("Echo Park, Los Angeles", "Chinatown, Los Angeles"),
("Echo Park, Los Angeles", "Downtown, Los Angeles"),
("Echo Park, Los Angeles", "East Hollywood, Los Angeles"),
("Echo Park, Los Angeles", "Elysian Valley, Los Angeles"),
("Echo Park, Los Angeles", "Glassell Park, Los Angeles"),
("Echo Park, Los Angeles", "Pico-Union, Los Angeles"),
("Echo Park, Los Angeles", "Silver Lake, Los Angeles"),
("Echo Park, Los Angeles", "Westlake, Los Angeles"),
("El Sereno, Los Angeles", "Chinatown, Los Angeles"),
("El Sereno, Los Angeles", "Highland Park, Los Angeles"),
("El Sereno, Los Angeles", "Lincoln Heights, Los Angeles"),
("El Sereno, Los Angeles", "Montecito Heights, Los Angeles"),
("Elysian Valley, Los Angeles", "Atwater Village, Los Angeles"),
("Elysian Valley, Los Angeles", "Cypress Park, Los Angeles"),
("Elysian Valley, Los Angeles", "Echo Park, Los Angeles"),
("Elysian Valley, Los Angeles", "Glassell Park, Los Angeles"),
("Elysian Valley, Los Angeles", "Griffith Park, Los Angeles"),
("Elysian Valley, Los Angeles", "Lincoln Heights, Los Angeles"),
("Elysian Valley, Los Angeles", "Los Feliz, Los Angeles"),
("Encino, Los Angeles", "Reseda, Los Angeles"),
("Encino, Los Angeles", "Sherman Oaks, Los Angeles"),
("Encino, Los Angeles", "Studio City, Los Angeles"),
("Encino, Los Angeles", "Tarzana, Los Angeles"),
("Encino, Los Angeles", "Lake Balboa, Los Angeles"),
("Exposition Park, Los Angeles", "Adams-Normandie, Los Angeles"),
("Exposition Park, Los Angeles", "Arlington Heights, Los Angeles"),
("Exposition Park, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Exposition Park, Los Angeles", "Chesterfield Square, Los Angeles"),
("Exposition Park, Los Angeles", "Harvard Heights, Los Angeles"),
("Exposition Park, Los Angeles", "Harvard Park, Los Angeles"),
("Exposition Park, Los Angeles", "Jefferson Park, Los Angeles"),
("Exposition Park, Los Angeles", "Koreatown, Los Angeles"),
("Exposition Park, Los Angeles", "Leimert Park, Los Angeles"),
("Exposition Park, Los Angeles", "Pico-Union, Los Angeles"),
("Exposition Park, Los Angeles", "University Park, Los Angeles"),
("Exposition Park, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Exposition Park, Los Angeles", "Vermont Square, Los Angeles"),
("Exposition Park, Los Angeles", "West Adams, Los Angeles"),
("Fairfax, Los Angeles", "Beverly Grove, Los Angeles"),
("Fairfax, Los Angeles", "Carthay, Los Angeles"),
("Fairfax, Los Angeles", "Hancock Park, Los Angeles"),
("Fairfax, Los Angeles", "Hollywood, Los Angeles"),
("Fairfax, Los Angeles", "Larchmont, Los Angeles"),
("Fairfax, Los Angeles", "Mid-City, Los Angeles"),
("Fairfax, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Fairfax, Los Angeles", "Windsor Square, Los Angeles"),
("Florence, Los Angeles", "Broadway-Manchester, Los Angeles"),
("Florence, Los Angeles", "Chesterfield Square, Los Angeles"),
("Florence, Los Angeles", "Green Meadows, Los Angeles"),
("Florence, Los Angeles", "Harvard Park, Los Angeles"),
("Florence, Los Angeles", "Historic South-Central, Los Angeles"),
("Florence, Los Angeles", "South Park, Los Angeles"),
("Florence, Los Angeles", "Vermont Knolls, Los Angeles"),
("Florence, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Florence, Los Angeles", "Vermont Square, Los Angeles"),
("Florence, Los Angeles", "Vermont Vista, Los Angeles"),
("Glassell Park, Los Angeles", "Atwater Village, Los Angeles"),
("Glassell Park, Los Angeles", "Cypress Park, Los Angeles"),
("Glassell Park, Los Angeles", "Eagle Rock, Los Angeles"),
("Glassell Park, Los Angeles", "Highland Park, Los Angeles"),
("Glassell Park, Los Angeles", "Lincoln Heights, Los Angeles"),
("Glassell Park, Los Angeles", "Montecito Heights, Los Angeles"),
("Gramercy Park, Los Angeles", "Broadway-Manchester, Los Angeles"),
("Gramercy Park, Los Angeles", "Chesterfield Square, Los Angeles"),
("Gramercy Park, Los Angeles", "Harvard Park, Los Angeles"),
("Gramercy Park, Los Angeles", "Vermont Knolls, Los Angeles"),
("Gramercy Park, Los Angeles", "Vermont Vista, Los Angeles"),
("Granada Hills, Los Angeles", "Mission Hills, Los Angeles"),
("Granada Hills, Los Angeles", "North Hills, Los Angeles"),
("Granada Hills, Los Angeles", "Lake Balboa, Los Angeles"),
("Green Meadows, Los Angeles", "Broadway-Manchester, Los Angeles"),
("Green Meadows, Los Angeles", "Florence, Los Angeles"),
("Green Meadows, Los Angeles", "Vermont Vista, Los Angeles"),
("Green Meadows, Los Angeles", "Watts, Los Angeles"),
("Griffith Park, Los Angeles", "Atwater Village, Los Angeles"),
("Griffith Park, Los Angeles", "Elysian Valley, Los Angeles"),
("Griffith Park, Los Angeles", "Glassell Park, Los Angeles"),
("Griffith Park, Los Angeles", "Los Feliz, Los Angeles"),
("Hancock Park, Los Angeles", "Beverly Grove, Los Angeles"),
("Hancock Park, Los Angeles", "Carthay, Los Angeles"),
("Hancock Park, Los Angeles", "Downtown, Los Angeles"),
("Hancock Park, Los Angeles", "East Hollywood, Los Angeles"),
("Hancock Park, Los Angeles", "Fairfax, Los Angeles"),
("Hancock Park, Los Angeles", "Hollywood, Los Angeles"),
("Hancock Park, Los Angeles", "Larchmont, Los Angeles"),
("Hancock Park, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Hancock Park, Los Angeles", "Westlake, Los Angeles"),
("Hancock Park, Los Angeles", "Windsor Square, Los Angeles"),
("Hansen Dam, Los Angeles", "Lake View Terrace, Los Angeles"),
("Hansen Dam, Los Angeles", "Pacoima, Los Angeles"),
("Hansen Dam, Los Angeles", "Sunland, Los Angeles"),
("Hansen Dam, Los Angeles", "Tujunga, Los Angeles"),
("Harbor City, Los Angeles", "Harbor Gateway, Los Angeles"),
("Harbor City, Los Angeles", "Wilmington, Los Angeles"),
("Harbor Gateway, Los Angeles", "Harbor City, Los Angeles"),
("Harvard Heights, Los Angeles", "Adams-Normandie, Los Angeles"),
("Harvard Heights, Los Angeles", "Arlington Heights, Los Angeles"),
("Harvard Heights, Los Angeles", "Exposition Park, Los Angeles"),
("Harvard Heights, Los Angeles", "Jefferson Park, Los Angeles"),
("Harvard Heights, Los Angeles", "Koreatown, Los Angeles"),
("Harvard Heights, Los Angeles", "Larchmont, Los Angeles"),
("Harvard Heights, Los Angeles", "Mid-City, Los Angeles"),
("Harvard Heights, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Harvard Heights, Los Angeles", "Pico-Union, Los Angeles"),
("Harvard Heights, Los Angeles", "University Park, Los Angeles"),
("Harvard Heights, Los Angeles", "Vermont Square, Los Angeles"),
("Harvard Heights, Los Angeles", "West Adams, Los Angeles"),
("Harvard Heights, Los Angeles", "Westlake, Los Angeles"),
("Harvard Heights, Los Angeles", "Windsor Square, Los Angeles"),
("Harvard Park, Los Angeles", "Adams-Normandie, Los Angeles"),
("Harvard Park, Los Angeles", "Chesterfield Square, Los Angeles"),
("Harvard Park, Los Angeles", "Exposition Park, Los Angeles"),
("Harvard Park, Los Angeles", "Florence, Los Angeles"),
("Harvard Park, Los Angeles", "Gramercy Park, Los Angeles"),
("Harvard Park, Los Angeles", "Hyde Park, Los Angeles"),
("Harvard Park, Los Angeles", "Vermont Knolls, Los Angeles"),
("Harvard Park, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Harvard Park, Los Angeles", "Vermont Square, Los Angeles"),
("Harvard Park, Los Angeles", "West Adams, Los Angeles"),
("Highland Park, Los Angeles", "Chinatown, Los Angeles"),
("Highland Park, Los Angeles", "Cypress Park, Los Angeles"),
("Highland Park, Los Angeles", "Eagle Rock, Los Angeles"),
("Highland Park, Los Angeles", "Glassell Park, Los Angeles"),
("Highland Park, Los Angeles", "Lincoln Heights, Los Angeles"),
("Highland Park, Los Angeles", "Montecito Heights, Los Angeles"),
("Historic South-Central, Los Angeles", "Central-Alameda, Los Angeles"),
("Historic South-Central, Los Angeles", "Exposition Park, Los Angeles"),
("Historic South-Central, Los Angeles", "Florence, Los Angeles"),
("Historic South-Central, Los Angeles", "Leimert Park, Los Angeles"),
("Historic South-Central, Los Angeles", "South Park, Los Angeles"),
("Historic South-Central, Los Angeles", "University Park, Los Angeles"),
("Hollywood Hills, Los Angeles", "Hollywood, Los Angeles"),
("Hollywood Hills West, Los Angeles", "Studio City, Los Angeles"),
("Hollywood, Los Angeles", "East Hollywood, Los Angeles"),
("Hollywood, Los Angeles", "Hancock Park, Los Angeles"),
("Hollywood, Los Angeles", "Hollywood Hills, Los Angeles"),
("Hollywood, Los Angeles", "Larchmont, Los Angeles"),
("Hollywood, Los Angeles", "Silver Lake, Los Angeles"),
("Hollywood, Los Angeles", "Windsor Square, Los Angeles"),
("Hyde Park, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Hyde Park, Los Angeles", "Chesterfield Square, Los Angeles"),
("Hyde Park, Los Angeles", "Harvard Park, Los Angeles"),
("Hyde Park, Los Angeles", "Leimert Park, Los Angeles"),
("Hyde Park, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Hyde Park, Los Angeles", "Vermont Square, Los Angeles"),
("Jefferson Park, Los Angeles", "Adams-Normandie, Los Angeles"),
("Jefferson Park, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Jefferson Park, Los Angeles", "Exposition Park, Los Angeles"),
("Jefferson Park, Los Angeles", "Harvard Heights, Los Angeles"),
("Jefferson Park, Los Angeles", "Hyde Park, Los Angeles"),
("Jefferson Park, Los Angeles", "Mid-City, Los Angeles"),
("Jefferson Park, Los Angeles", "University Park, Los Angeles"),
("Jefferson Park, Los Angeles", "West Adams, Los Angeles"),
("Koreatown, Los Angeles", "Adams-Normandie, Los Angeles"),
("Koreatown, Los Angeles", "Arlington Heights, Los Angeles"),
("Koreatown, Los Angeles", "Downtown, Los Angeles"),
("Koreatown, Los Angeles", "East Hollywood, Los Angeles"),
("Koreatown, Los Angeles", "Exposition Park, Los Angeles"),
("Koreatown, Los Angeles", "Hancock Park, Los Angeles"),
("Koreatown, Los Angeles", "Harvard Heights, Los Angeles"),
("Koreatown, Los Angeles", "Hollywood, Los Angeles"),
("Koreatown, Los Angeles", "Larchmont, Los Angeles"),
("Koreatown, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Koreatown, Los Angeles", "Pico-Union, Los Angeles"),
("Koreatown, Los Angeles", "Vermont Square, Los Angeles"),
("Koreatown, Los Angeles", "West Adams, Los Angeles"),
("Koreatown, Los Angeles", "Westlake, Los Angeles"),
("Koreatown, Los Angeles", "Windsor Square, Los Angeles"),
("Lake View Terrace, Los Angeles", "Hansen Dam, Los Angeles"),
("Lake View Terrace, Los Angeles", "Pacoima, Los Angeles"),
("Lake View Terrace, Los Angeles", "Sunland, Los Angeles"),
("Lake View Terrace, Los Angeles", "Tujunga, Los Angeles"),
("Larchmont, Los Angeles", "Beverly Grove, Los Angeles"),
("Larchmont, Los Angeles", "Downtown, Los Angeles"),
("Larchmont, Los Angeles", "East Hollywood, Los Angeles"),
("Larchmont, Los Angeles", "Fairfax, Los Angeles"),
("Larchmont, Los Angeles", "Hancock Park, Los Angeles"),
("Larchmont, Los Angeles", "Harvard Heights, Los Angeles"),
("Larchmont, Los Angeles", "Hollywood, Los Angeles"),
("Larchmont, Los Angeles", "Koreatown, Los Angeles"),
("Larchmont, Los Angeles", "Windsor Square, Los Angeles"),
("Leimert Park, Los Angeles", "Adams-Normandie, Los Angeles"),
("Leimert Park, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Leimert Park, Los Angeles", "Chesterfield Square, Los Angeles"),
("Leimert Park, Los Angeles", "Exposition Park, Los Angeles"),
("Leimert Park, Los Angeles", "Hyde Park, Los Angeles"),
("Leimert Park, Los Angeles", "Vermont Square, Los Angeles"),
("Leimert Park, Los Angeles", "West Adams, Los Angeles"),
("Lincoln Heights, Los Angeles", "Boyle Heights, Los Angeles"),
("Lincoln Heights, Los Angeles", "Chinatown, Los Angeles"),
("Lincoln Heights, Los Angeles", " Park, Los Angeles"),
("Lincoln Heights, Los Angeles", "El Sereno, Los Angeles"),
("Lincoln Heights, Los Angeles", "Elysian Valley, Los Angeles"),
("Lincoln Heights, Los Angeles", "Glassell Park, Los Angeles"),
("Lincoln Heights, Los Angeles", "Highland Park, Los Angeles"),
("Lincoln Heights, Los Angeles", "Montecito Heights, Los Angeles"),
("Los Feliz, Los Angeles", "Atwater Village, Los Angeles"),
("Los Feliz, Los Angeles", "East Hollywood, Los Angeles"),
("Los Feliz, Los Angeles", "Griffith Park, Los Angeles"),
("Mar Vista, Los Angeles", "Del Rey, Los Angeles"),
("Mar Vista, Los Angeles", "Mid-City, Los Angeles"),
("Mar Vista, Los Angeles", "Palms, Los Angeles"),
("Mar Vista, Los Angeles", "Playa Vista, Los Angeles"),
("Mar Vista, Los Angeles", "Rancho Park, Los Angeles"),
("Mar Vista, Los Angeles", "Sawtelle, Los Angeles"),
("Mar Vista, Los Angeles", "Venice, Los Angeles"),
("Mar Vista, Los Angeles", "West Los Angeles, Los Angeles"),
("Mid-City, Los Angeles", "Adams-Normandie, Los Angeles"),
("Mid-City, Los Angeles", "Arlington Heights, Los Angeles"),
("Mid-City, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Mid-City, Los Angeles", "Beverly Grove, Los Angeles"),
("Mid-City, Los Angeles", "Carthay, Los Angeles"),
("Mid-City, Los Angeles", "Fairfax, Los Angeles"),
("Mid-City, Los Angeles", "Harvard Heights, Los Angeles"),
("Mid-City, Los Angeles", "Jefferson Park, Los Angeles"),
("Mid-City, Los Angeles", "Mar Vista, Los Angeles"),
("Mid-City, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Mid-City, Los Angeles", "Palms, Los Angeles"),
("Mid-City, Los Angeles", "Pico-Robertson, Los Angeles"),
("Mid-City, Los Angeles", "Pico-Union, Los Angeles"),
("Mid-City, Los Angeles", "Rancho Park, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Arlington Heights, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Beverly Grove, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Carthay, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Fairfax, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Hancock Park, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Harvard Heights, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Mid-City, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Pico-Robertson, Los Angeles"),
("Mid-Wilshire, Los Angeles", "Windsor Square, Los Angeles"),
("Mission Hills, Los Angeles", "Arleta, Los Angeles"),
("Mission Hills, Los Angeles", "Granada Hills, Los Angeles"),
("Mission Hills, Los Angeles", "North Hills, Los Angeles"),
("Mission Hills, Los Angeles", "Panorama City, Los Angeles"),
("Mission Hills, Los Angeles", "Van Nuys, Los Angeles"),
("Montecito Heights, Los Angeles", "Chinatown, Los Angeles"),
("Montecito Heights, Los Angeles", "Cypress Park, Los Angeles"),
("Montecito Heights, Los Angeles", "El Sereno, Los Angeles"),
("Montecito Heights, Los Angeles", "Highland Park, Los Angeles"),
("Montecito Heights, Los Angeles", "Lincoln Heights, Los Angeles"),
("North Hills, Los Angeles", "Granada Hills, Los Angeles"),
("North Hills, Los Angeles", "Mission Hills, Los Angeles"),
("North Hills, Los Angeles", "Northridge, Los Angeles"),
("North Hills, Los Angeles", "Panorama City, Los Angeles:"),
("North Hills, Los Angeles", "Van Nuys, Los Angeles"),
("North Hollywood, Los Angeles", "Panorama City, Los Angeles"),
("North Hollywood, Los Angeles", "Studio City, Los Angeles"),
("North Hollywood, Los Angeles", "Sun Valley, Los Angeles"),
("North Hollywood, Los Angeles", "Lake, Los Angeles"),
("North Hollywood, Los Angeles", "Valley Glen, Los Angeles"),
("North Hollywood, Los Angeles", "Valley Village, Los Angeles"),
("Northridge, Los Angeles", "Canoga Park, Los Angeles"),
("Northridge, Los Angeles", "Granada Hills, Los Angeles"),
("Northridge, Los Angeles", "North Hills, Los Angeles"),
("Northridge, Los Angeles", "Reseda, Los Angeles"),
("Northridge, Los Angeles", "Winnetka, Los Angeles"),
("Pacific Palisades, Los Angeles", "Brentwood, Los Angeles"),
("Pacoima, Los Angeles", "Arleta, Los Angeles"),
("Pacoima, Los Angeles", "Hansen Dam, Los Angeles"),
("Pacoima, Los Angeles", "Lake View Terrace, Los Angeles"),
("Pacoima, Los Angeles", "Shadow Hills, Los Angeles"),
("Palms, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Palms, Los Angeles", "Century City, Los Angeles"),
("Palms, Los Angeles", "Cheviot Hills, Los Angeles"),
("Palms, Los Angeles", "Mar Vista, Los Angeles"),
("Palms, Los Angeles", "Mid-City, Los Angeles"),
("Palms, Los Angeles", "Rancho Park, Los Angeles"),
("Palms, Los Angeles", "West Los Angeles, Los Angeles"),
("Palms, Los Angeles", "Westwood, Los Angeles"),
("Panorama City, Los Angeles", "Arleta, Los Angeles"),
("Panorama City, Los Angeles", "North Hills, Los Angeles"),
("Panorama City, Los Angeles", "North Hollywood, Los Angeles"),
("Panorama City, Los Angeles", "Sherman Oaks, Los Angeles"),
("Panorama City, Los Angeles", "Sun Valley, Los Angeles"),
("Panorama City, Los Angeles", "Van Nuys, Los Angeles"),
("Panorama City, Los Angeles", "Lake Balboa, Los Angeles"),
("Pico-Robertson, Los Angeles", "Beverly Grove, Los Angeles"),
("Pico-Robertson, Los Angeles", "Beverlywood, Los Angeles"),
("Pico-Robertson, Los Angeles", "Carthay, Los Angeles"),
("Pico-Robertson, Los Angeles", "Century City, Los Angeles"),
("Pico-Robertson, Los Angeles", "Mid-City, Los Angeles"),
("Pico-Robertson, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Pico-Robertson, Los Angeles", "Rancho Park, Los Angeles"),
("Pico-Robertson, Los Angeles", "Sawtelle, Los Angeles"),
("Pico-Robertson, Los Angeles", "West Los Angeles, Los Angeles"),
("Pico-Robertson, Los Angeles", "Westwood, Los Angeles"),
("Pico-Union, Los Angeles", "Adams-Normandie, Los Angeles"),
("Pico-Union, Los Angeles", "Arlington Heights, Los Angeles"),
("Pico-Union, Los Angeles", "Chinatown, Los Angeles"),
("Pico-Union, Los Angeles", "Echo Park, Los Angeles"),
("Pico-Union, Los Angeles", "Exposition Park, Los Angeles"),
("Pico-Union, Los Angeles", "Harvard Heights, Los Angeles"),
("Pico-Union, Los Angeles", "Koreatown, Los Angeles"),
("Pico-Union, Los Angeles", "Mid-City, Los Angeles"),
("Pico-Union, Los Angeles", "Silver Lake, Los Angeles"),
("Pico-Union, Los Angeles", "University Park, Los Angeles"),
("Pico-Union, Los Angeles", "West Adams, Los Angeles"),
("Pico-Union, Los Angeles", "Westlake, Los Angeles"),
("Playa del Rey, Los Angeles", "Westchester, Los Angeles"),
("Playa Vista, Los Angeles", "Del Rey, Los Angeles"),
("Playa Vista, Los Angeles", "Mar Vista, Los Angeles"),
("Rancho Park, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Rancho Park, Los Angeles", "Beverlywood, Los Angeles"),
("Rancho Park, Los Angeles", "Century City, Los Angeles"),
("Rancho Park, Los Angeles", "Cheviot Hills, Los Angeles"),
("Rancho Park, Los Angeles", "Mid-City, Los Angeles"),
("Rancho Park, Los Angeles", "Palms, Los Angeles"),
("Rancho Park, Los Angeles", "Pico-Robertson, Los Angeles"),
("Rancho Park, Los Angeles", "Sawtelle, Los Angeles"),
("Rancho Park, Los Angeles", "West Los Angeles, Los Angeles"),
("Rancho Park, Los Angeles", "Westwood, Los Angeles"),
("Reseda, Los Angeles", "Encino, Los Angeles"),
("Reseda, Los Angeles", "Northridge, Los Angeles"),
("Reseda, Los Angeles", "Tarzana, Los Angeles"),
("Reseda, Los Angeles", "Van Nuys, Los Angeles"),
("Reseda, Los Angeles", "Winnetka, Los Angeles"),
("Reseda, Los Angeles", "Lake Balboa, Los Angeles"),
("San Pedro, Los Angeles", "Harbor City, Los Angeles"),
("Sawtelle, Los Angeles", "Beverlywood, Los Angeles"),
("Sawtelle, Los Angeles", "Century City, Los Angeles"),
("Sawtelle, Los Angeles", "Del Rey, Los Angeles"),
("Sawtelle, Los Angeles", "Mar Vista, Los Angeles"),
("Sawtelle, Los Angeles", "Pico-Robertson, Los Angeles"),
("Sawtelle, Los Angeles", "Rancho Park, Los Angeles"),
("Sawtelle, Los Angeles", "West Los Angeles, Los Angeles"),
("Sepulveda Basin, Los Angeles", "Van Nuys, Los Angeles"),
("Shadow Hills, Los Angeles", "Pacoima, Los Angeles"),
("Shadow Hills, Los Angeles", "Sunland, Los Angeles"),
("Shadow Hills, Los Angeles", "Sun Valley, Los Angeles"),
("Shadow Hills, Los Angeles", "Tujunga, Los Angeles"),
("Sherman Oaks, Los Angeles", "Encino, Los Angeles"),
("Sherman Oaks, Los Angeles", "Studio City, Los Angeles"),
("Sherman Oaks, Los Angeles", "Valley Glen, Los Angeles"),
("Sherman Oaks, Los Angeles", "Valley Village, Los Angeles"),
("Silver Lake, Los Angeles", "Chinatown, Los Angeles"),
("Silver Lake, Los Angeles", "Downtown, Los Angeles"),
("Silver Lake, Los Angeles", "East Hollywood, Los Angeles"),
("Silver Lake, Los Angeles", "Echo Park, Los Angeles"),
("Silver Lake, Los Angeles", "Hollywood, Los Angeles"),
("Silver Lake, Los Angeles", "Los Feliz, Los Angeles"),
("Silver Lake, Los Angeles", "Pico-Union, Los Angeles"),
("Silver Lake, Los Angeles", "Westlake, Los Angeles"),
("South Park, Los Angeles", "Chesterfield Square, Los Angeles"),
("South Park, Los Angeles", "Florence, Los Angeles"),
("South Park, Los Angeles", "Historic South-Central, Los Angeles"),
("South Park, Los Angeles", "Vermont-Slauson, Los Angeles"),
("South Park, Los Angeles", "Vermont Square, Los Angeles"),
("Studio City, Los Angeles", "North Hollywood, Los Angeles"),
("Studio City, Los Angeles", "Sherman Oaks, Los Angeles"),
("Studio City, Los Angeles", "Toluca Lake, Los Angeles"),
("Studio City, Los Angeles", "Valley Village, Los Angeles"),
("Sunland, Los Angeles", "Hansen Dam, Los Angeles"),
("Sunland, Los Angeles", "Lake View Terrace, Los Angeles"),
("Sunland, Los Angeles", "Pacoima, Los Angeles"),
("Sunland, Los Angeles", "Shadow Hills, Los Angeles"),
("Sun Valley, Los Angeles", "North Hollywood, Los Angeles"),
("Sun Valley, Los Angeles", "Panorama City, Los Angeles"),
("Tarzana, Los Angeles", "Encino, Los Angeles"),
("Tarzana, Los Angeles", "Reseda, Los Angeles"),
("Tarzana, Los Angeles", "Winnetka, Los Angeles"),
("Tarzana, Los Angeles", "Woodland Hills, Los Angeles"),
("Toluca Lake, Los Angeles", "Hollywood Hills, Los Angeles"),
("Toluca Lake, Los Angeles", "North Hollywood, Los Angeles"),
("Toluca Lake, Los Angeles", "Valley Village, Los Angeles"),
("Tujunga, Los Angeles", "Hansen Dam, Los Angeles"),
("Tujunga, Los Angeles", "Lake View Terrace, Los Angeles"),
("Tujunga, Los Angeles", "Pacoima, Los Angeles"),
("Tujunga, Los Angeles", "Shadow Hills, Los Angeles"),
("University Park, Los Angeles", "Adams-Normandie, Los Angeles"),
("University Park, Los Angeles", "Arlington Heights, Los Angeles"),
("University Park, Los Angeles", "Exposition Park, Los Angeles"),
("University Park, Los Angeles", "Jefferson Park, Los Angeles"),
("University Park, Los Angeles", "Pico-Union, Los Angeles"),
("University Park, Los Angeles", "Vermont-Slauson, Los Angeles"),
("University Park, Los Angeles", "Vermont Square, Los Angeles"),
("University Park, Los Angeles", "West Adams, Los Angeles"),
("University Park, Los Angeles", "Westlake, Los Angeles"),
("Valley Glen, Los Angeles", "North Hollywood, Los Angeles"),
("Valley Glen, Los Angeles", "Sherman Oaks, Los Angeles"),
("Valley Village, Los Angeles", "North Hollywood, Los Angeles"),
("Valley Village, Los Angeles", "Sherman Oaks, Los Angeles"),
("Valley Village, Los Angeles", "Studio City, Los Angeles"),
("Van Nuys, Los Angeles", "Mission Hills, Los Angeles"),
("Van Nuys, Los Angeles", "North Hills, Los Angeles"),
("Van Nuys, Los Angeles", "Panorama City, Los Angeles"),
("Van Nuys, Los Angeles", "Reseda, Los Angeles"),
("Van Nuys, Los Angeles", "Sepulveda Basin, Los Angeles"),
("Van Nuys, Los Angeles", "Lake Balboa, Los Angeles"),
("Venice, Los Angeles", "Del Rey, Los Angeles"),
("Venice, Los Angeles", "Mar Vista, Los Angeles"),
("Vermont Knolls, Los Angeles", "Broadway-Manchester, Los Angeles"),
("Vermont Knolls, Los Angeles", "Chesterfield Square, Los Angeles"),
("Vermont Knolls, Los Angeles", "Florence, Los Angeles"),
("Vermont Knolls, Los Angeles", "Gramercy Park, Los Angeles"),
("Vermont Knolls, Los Angeles", "Harvard Park, Los Angeles"),
("Vermont Knolls, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Vermont Knolls, Los Angeles", "Vermont Square, Los Angeles"),
("Vermont Knolls, Los Angeles", "Vermont Vista, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Broadway-Manchester, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Chesterfield Square, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Exposition Park, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Florence, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Harvard Park, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Hyde Park, Los Angeles"),
("Vermont-Slauson, Los Angeles", "South Park, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Vermont Knolls, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Vermont Square, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Vermont Vista, Los Angeles"),
("Vermont-Slauson, Los Angeles", "Watts, Los Angeles"),
("Vermont Square, Los Angeles", "Adams-Normandie, Los Angeles"),
("Vermont Square, Los Angeles", "Baldwin Hills/Crenshaw, Los Angeles"),
("Vermont Square, Los Angeles", "Chesterfield Square, Los Angeles"),
("Vermont Square, Los Angeles", "Exposition Park, Los Angeles"),
("Vermont Square, Los Angeles", "Harvard Park, Los Angeles"),
("Vermont Square, Los Angeles", "Historic South-Central, Los Angeles"),
("Vermont Square, Los Angeles", "Hyde Park, Los Angeles"),
("Vermont Square, Los Angeles", "Leimert Park, Los Angeles"),
("Vermont Square, Los Angeles", "South Park, Los Angeles"),
("Vermont Square, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Vermont Square, Los Angeles", "West Adams, Los Angeles"),
("Vermont Vista, Los Angeles", "Broadway-Manchester, Los Angeles"),
("Vermont Vista, Los Angeles", "Florence, Los Angeles"),
("Vermont Vista, Los Angeles", "Gramercy Park, Los Angeles"),
("Vermont Vista, Los Angeles", "Green Meadows, Los Angeles"),
("Vermont Vista, Los Angeles", "Harvard Park, Los Angeles"),
("Vermont Vista, Los Angeles", "South Park, Los Angeles"),
("Vermont Vista, Los Angeles", "Vermont Knolls, Los Angeles"),
("Vermont Vista, Los Angeles", "Vermont-Slauson, Los Angeles"),
("Vermont Vista, Los Angeles", "Watts, Los Angeles"),
("Watts, Los Angeles", "Broadway-Manchester, Los Angeles"),
("Watts, Los Angeles", "Central-Alameda, Los Angeles"),
("Watts, Los Angeles", "Florence, Los Angeles"),
("Watts, Los Angeles", "Vermont Vista, Los Angeles"),
("West Adams, Los Angeles", "Adams-Normandie, Los Angeles"),
("West Adams, Los Angeles", "Arlington Heights, Los Angeles"),
("West Adams, Los Angeles", "Chesterfield Square, Los Angeles"),
("West Adams, Los Angeles", "Downtown, Los Angeles"),
("West Adams, Los Angeles", "Exposition Park, Los Angeles"),
("West Adams, Los Angeles", "Harvard Heights, Los Angeles"),
("West Adams, Los Angeles", "Harvard Park, Los Angeles"),
("West Adams, Los Angeles", "Jefferson Park, Los Angeles"),
("West Adams, Los Angeles", "Koreatown, Los Angeles"),
("West Adams, Los Angeles", "Mid-City, Los Angeles"),
("West Adams, Los Angeles", "Pico-Union, Los Angeles"),
("West Adams, Los Angeles", "University Park, Los Angeles"),
("West Adams, Los Angeles", "Vermont Square, Los Angeles"),
("West Adams, Los Angeles", "Westlake, Los Angeles"),
("Westchester, Los Angeles", "Playa del Rey, Los Angeles"),
("Westchester, Los Angeles", "Playa Vista, Los Angeles"),
("West Hills, Los Angeles", "Canoga Park, Los Angeles"),
("West Hills, Los Angeles", "Winnetka, Los Angeles"),
("Westlake, Los Angeles", "Adams-Normandie, Los Angeles"),
("Westlake, Los Angeles", "Downtown, Los Angeles"),
("Westlake, Los Angeles", "East Hollywood, Los Angeles"),
("Westlake, Los Angeles", "Echo Park, Los Angeles"),
("Westlake, Los Angeles", "Koreatown, Los Angeles"),
("Westlake, Los Angeles", "Pico-Union, Los Angeles"),
("Westlake, Los Angeles", "Silver Lake, Los Angeles"),
("Westlake, Los Angeles", "University Park, Los Angeles"),
("Westlake, Los Angeles", "West Adams, Los Angeles"),
("Westlake, Los Angeles", "Windsor Square, Los Angeles"),
("West Los Angeles, Los Angeles", "Beverlywood, Los Angeles"),
("West Los Angeles, Los Angeles", "Century City, Los Angeles"),
("West Los Angeles, Los Angeles", "Cheviot Hills, Los Angeles"),
("West Los Angeles, Los Angeles", "Palms, Los Angeles"),
("West Los Angeles, Los Angeles", "Pico-Robertson, Los Angeles"),
("West Los Angeles, Los Angeles", "Rancho Park, Los Angeles"),
("West Los Angeles, Los Angeles", "Sawtelle, Los Angeles"),
("West Los Angeles, Los Angeles", "Westwood, Los Angeles"),
("Westwood, Los Angeles", "Brentwood, Los Angeles"),
("Westwood, Los Angeles", "Palms, Los Angeles"),
("Westwood, Los Angeles", "Pico-Robertson, Los Angeles"),
("Westwood, Los Angeles", "Rancho Park, Los Angeles"),
("Westwood, Los Angeles", "West Los Angeles, Los Angeles"),
("Wilmington, Los Angeles", "Harbor City, Los Angeles"),
("Windsor Square, Los Angeles", "Beverly Grove, Los Angeles"),
("Windsor Square, Los Angeles", "Fairfax, Los Angeles"),
("Windsor Square, Los Angeles", "Hancock Park, Los Angeles"),
("Windsor Square, Los Angeles", "Harvard Heights, Los Angeles"),
("Windsor Square, Los Angeles", "Hollywood, Los Angeles"),
("Windsor Square, Los Angeles", "Koreatown, Los Angeles"),
("Windsor Square, Los Angeles", "Larchmont, Los Angeles"),
("Windsor Square, Los Angeles", "Mid-Wilshire, Los Angeles"),
("Windsor Square, Los Angeles", "Westlake, Los Angeles"),
("Winnetka, Los Angeles", "Canoga Park, Los Angeles"),
("Winnetka, Los Angeles", "Chatsworth, Los Angeles"),
("Winnetka, Los Angeles", "Northridge, Los Angeles"),
("Winnetka, Los Angeles", "Reseda, Los Angeles"),
("Winnetka, Los Angeles", "West Hills, Los Angeles"),
("Woodland Hills, Los Angeles", "Tarzana, Los Angeles"),
("Lake Balboa, Los Angeles", "Encino, Los Angeles"),
("Lake Balboa, Los Angeles", "Granada Hills, Los Angeles"),
("Lake Balboa, Los Angeles", "Panorama City, Los Angeles"),
("Lake Balboa, Los Angeles", "Reseda, Los Angeles"),
("Lake Balboa, Los Angeles", "Van Nuys, Los Angeles"),
("Lake Balboa, Los Angeles", "Winnetka, Los Angeles")]


poverty_data={"Adams-Normandie, Los Angeles, 90.24% Not White": 24.92,  #manually entered racial data and percent families living below the poverty line
"Arleta, Los Angeles, 91.27% Not White": 9.43, 
"Arlington Heights, Los Angeles, 94.39% Not White": 21.64, 
"Atwater Village, Los Angeles, 60.85% Not White": 12.61, 
"Baldwin Hills/Crenshaw, Los Angeles, 91.58% Not White": 20.69, 
"Bel-Air, Los Angeles, 26.79% Not White": 6.27, 
"Beverly Crest, Los Angeles, 17.56% Not White": 6.23, 
"Beverly Grove, Los Angeles,18 % Not White": 9.88, 
"Beverlywood, Los Angeles, 40.05% Not White": 4.06, 
"Boyle Heights, Los Angeles, 97.36% Not White": 22.96, 
"Brentwood, Los Angeles, 23.88% Not White": 6.09, 
"Broadway-Manchester, Los Angeles, 99.28% Not White": 29.68, 
"Canoga Park, Los Angeles, 76.6% Not White": 15.74, 
"Carthay, Los Angeles, 23.27% Not White": 4.67, 
"Central-Alameda, Los Angeles, 99.31% Not White": 27.41, 
"Century City, Los Angeles, 39.67% Not White": 6.82, 
"Chatsworth, Los Angeles, 60% Not White": 5.33, 
"Chatsworth Reservoir, Los Angeles, 55% Not White": 3.23, 
"Chesterfield Square, Los Angeles, 98.5% Not White": 19.2, 
"Cheviot Hills, Los Angeles, 23.1% Not White": 2.02, 
"Chinatown, Los Angeles, 85.25% Not White": 29.52, 
"Cypress Park, Los Angeles, 86.42% Not White": 20.2, 
"Del Rey, Los Angeles, 59.36% Not White": 14.69, 
"Downtown, Los Angeles, 74.66% Not White": 30.37, 
"Eagle Rock, Los Angeles, 67.99% Not White": 10.14, 
"East Hollywood, Los Angeles, 69.28% Not White": 21.82, 
"Echo Park, Los Angeles, 66.91% Not White": 16.78, 
"El Sereno, Los Angeles, 90.79% Not White": 16.17, 
"Elysian Park, Los Angeles, 91.61% Not White": 21.51, 
"Elysian Valley, Los Angeles, 83.38% Not White": 7.18, 
"Encino, Los Angeles, 25.19% Not White": 7.9, 
"Exposition Park, Los Angeles, 97.73% Not White": 24.09, 
"Fairfax, Los Angeles, 39.51% Not White": 9.46, 
"Florence, Los Angeles, 99.34% Not White": 23.73, 
"Glassell Park, Los Angeles, 74.67% Not White": 12.59, 
"Gramercy Park, Los Angeles, 97.69% Not White": 10, 
"Granada Hills, Los Angeles, 58.71% Not White": 8.15, 
"Green Meadows, Los Angeles, 99.78% Not White": 23.3, 
"Griffith Park, Los Angeles, 37.64% Not White": 0, 
"Hancock Park, Los Angeles, 39.55% Not White": 6.69, 
"Hansen Dam, Los Angeles, 93.75% Not White": 0, 
"Harbor City, Los Angeles, 83.25% Not White": 13.68, 
"Harbor Gateway, Los Angeles, 92.69% Not White": 15.45, 
"Harvard Heights, Los Angeles, 94.21% Not White": 23.5, 
"Harvard Park, Los Angeles, 98.2% Not White": 17.25, 
"Highland Park, Los Angeles, 78.36% Not White": 12.73, 
"Historic South-Central, Los Angeles, 97.75% Not White": 31.08, 
"Hollywood Hills, Los Angeles, 34.92% Not White": 9.77, 
"Hollywood Hills West, Los Angeles, 34.92% Not White": 7.05, 
"Hollywood, Los Angeles, 53.24% Not White": 18.05, 
"Hyde Park, Los Angeles, 95.69% Not White": 19.02, 
"Jefferson Park, Los Angeles, 90.84% Not White": 20.52, 
"Koreatown, Los Angeles, 90.11% Not White": 20.98, 
"Lake View Terrace, Los Angeles, 79% Not White": 7.36, 
"Larchmont, Los Angeles, 46.28% Not White": 11.09, 
"Leimert Park, Los Angeles, 94.78% Not White": 17.42, 
"Lincoln Heights, Los Angeles, 92.18% Not White": 22.61, 
"Los Feliz, Los Angeles, 37.64% Not White": 9.22, 
"Manchester Square, Los Angeles, 95.69% Not White": 22.21, 
"Mar Vista, Los Angeles, 49.28% Not White": 7.81, 
"Mid-City, Los Angeles, 84.97% Not White": 13.42, 
"Mid-Wilshire, Los Angeles, 38.56% Not White": 12.71, 
"Mission Hills, Los Angeles, 83.66% Not White": 9.8, 
"Montecito Heights, Los Angeles, 78.69% Not White": 13.06, 
"Mount Washington, Los Angeles, 49.84% Not White": 7.89, 
"North Hills, Los Angeles, 83.66% Not White": 17.58, 
"North Hollywood, Los Angeles, 68.54% Not White": 18.45, 
"Northridge, Los Angeles, 62.21% Not White": 14.08, 
"Pacific Palisades, Los Angeles, 18.62% Not White": 4.71, 
"Pacoima, Los Angeles, 97.54% Not White": 17.71, 
"Palms, Los Angeles, 59.18% Not White": 7.7, 
"Panorama City, Los Angeles, 89.2% Not White": 19.67, 
"Pico-Robertson, Los Angeles, 27% Not White": 10.63, 
"Pico-Union, Los Angeles, 94.95% Not White": 27.48, 
"Playa del Rey, Los Angeles, 35.72% Not White": 5.43, 
"Playa Vista, Los Angeles, 43.11% Not White": 4.88, 
"Porter Ranch, Los Angeles, 58.57% Not White": 5.51, 
"Rancho Park, Los Angeles, 42.16% Not White": 7.55, 
"Reseda, Los Angeles, 75.35% Not White": 12.98,
"San Pedro, Los Angeles, 68.04% Not White": 13.47, 
"Sawtelle, Los Angeles, 50% Not White": 11.97, 
"Sepulveda Basin, Los Angeles, 60.98% Not White": 7.84, 
"Shadow Hills, Los Angeles, 27.43% Not White": 6.62, 
"Sherman Oaks, Los Angeles, 35.44% Not White": 7.5, 
"Silver Lake, Los Angeles, 56.64% Not White": 9.27, 
"South Park, Los Angeles, 99.15% Not White": 27.37, 
"Studio City, Los Angeles, 31.53% Not White": 7.01, 
"Sunland, Los Angeles, 39.39% Not White": 6.95, 
"Sun Valley, Los Angeles, 77.53% Not White": 12.72, 
"Sylmar, Los Angeles, 89.39% Not White": 13.37, 
"Tarzana, Los Angeles, 26.34% Not White": 8.69, 
"Toluca Lake, Los Angeles, 33.83% Not White": 7.03, 
"Tujunga, Los Angeles, 42.71% Not White": 13.73, 
"University Park, Los Angeles, 73.22% Not White": 47.16, 
"Valley Glen, Los Angeles, 49.98% Not White": 18.92, 
"Valley Village, Los Angeles, 44.72% Not White": 11.92, 
"Van Nuys, Los Angeles, 78.87% Not White": 20.41, 
"Venice, Los Angeles, 34.01% Not White": 9.56, 
"Vermont Knolls, Los Angeles, 98.43% Not White": 31.43, 
"Vermont-Slauson, Los Angeles, 98.23% Not White": 25.58, 
"Vermont Square, Los Angeles, 97.79% Not White": 21.2, 
"Vermont Vista, Los Angeles, 98.45% Not White": 27.38, 
"Watts, Los Angeles, 99.2% Not White": 32.61, 
"West Adams, Los Angeles, 89.8% Not White": 16.85, 
"Westchester, Los Angeles, 51.9% Not White": 6.94, 
"West Hills, Los Angeles, 39.6% Not White": 7.35, 
"Westlake, Los Angeles, 93.63% Not White": 39.35, 
"West Los Angeles, Los Angeles, 49.9% Not White": 10.15, 
"Westwood, Los Angeles, 50.34% Not White": 26.58, 
"Wilmington, Los Angeles, 96.47% Not White": 20.01, 
"Windsor Square, Los Angeles, 71.45% Not White": 10.33, 
"Winnetka, Los Angeles, 68.62% Not White": 17.76, 
"Woodland Hills, Los Angeles, 42.82% Not White": 8.66, 
"Lake Balboa, Los Angeles, 64.35% Not White": 11.08}
                
brackets = [
    (0, 10, "Under 10%", "lightgreen"),
    (10, 20, "10-20%", "yellow"),
    (20, 30, "20-30%", "orange"),
    (30, 40, "30-40%", "red"),
    (40, 100, "Over 40%", "black")
] #sets bracket for colorcoding nodes 

def get_poverty_info(node_name):
    for full_name in poverty_data:
        if node_name in full_name:
            return poverty_data[full_name], full_name.split(", ", 2)[-1]  # returns (rate, demographics)
    return 0, "Demographics unknown"
G = nx.Graph() #creats graph
G.add_edges_from(connections) #gets edges
pos = nx.spring_layout(G, seed=42, k=0.9)

# Create edge trace
edge_x, edge_y = [], []
for edge in G.edges():
    x0, y0 = pos[edge[0]]
    x1, y1 = pos[edge[1]]
    edge_x += [x0, x1, None]
    edge_y += [y0, y1, None]

edge_trace = go.Scatter(
    x=edge_x, y=edge_y,
    line=dict(width=0.5, color='gray'),
    hoverinfo='none',
    mode='lines'
)

# Organize node data by bracket
node_coords = {bracket[2]: {"x": [], "y": [], "text": []} for bracket in brackets}

# Assign nodes to brackets
for node in G.nodes():
    x, y = pos[node]
    poverty_rate, demographics = get_poverty_info(node)
    hover_label = f"{node}<br>Poverty Rate: {poverty_rate}%<br>{demographics}"

    # Assign bracket
    for (low, high, bracket, _) in brackets:
        if low <= poverty_rate < high:
            node_coords[bracket]["x"].append(x)
            node_coords[bracket]["y"].append(y)
            node_coords[bracket]["text"].append(hover_label)
            break

# Build node traces by bracket
node_traces = []
for (low, high, bracket, color) in brackets:
    trace = go.Scatter(
        x=node_coords[bracket]["x"],
        y=node_coords[bracket]["y"],
        mode='markers',
        name=bracket,
        hoverinfo='text',
        marker=dict(size=12, color=color, line_width=1),
        text=node_coords[bracket]["text"]
    )
    node_traces.append(trace)


fig = go.Figure(
    data=[edge_trace] + node_traces,
    layout=go.Layout(
        title="LA Neighborhoods by Poverty Rate (with Race Demographics)",
        width=1000,
        height=800,
        showlegend=True,
        hovermode='closest',
        margin=dict(b=10, l=10, r=10, t=40),
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        plot_bgcolor='white'
    )
)

fig.show()
fig.write_html("network_graph.html", include_plotlyjs='cdn')

```

<iframe src="network_graph.html" width="1000" height="800">

</iframe>

### Conclusions

1.  Strong correlation between the percent of non-white residents and poverty.

2.  Poorest neighborhoods are the most connected (nodes with the highest degrees).

3.  Impoverished neighborhoods are primarily connected to other impoverished neighborhoods (and similarly, wealthy neighborhoods are connected to other wealthy neighborhoods).

### Limitations

Firstly, transportation data does not represent an average across all days and times of day. The data was collected at 11 AM on a Saturday because that is when the code was run. Similarly, the directions were taken from an arbitrarily determined “center” of each neighborhood by Google Directions.

There is also an inconsistency between the counting methods and the actual graph. When counting (Figure 1), each ordered pair was considered separately, i.e., $(v, u) \neq (u, v)$, but this distinction is not represented in the graph (Figure 3), where edges are treated as undirected.

Finally, in simplifying the data for the final visualization, I chose to group all non-white racial categories into a single category to highlight neighborhood diversity. In doing this, I acknowledge that I combined distinct cultures, identities, and heritages into a single label of “diversity.” This risks oversimplifying and diminishing the uniqueness of the communities represented. In the future, I could represent racial demographics with more nuance and specificity.

Link to full paper: <https://docs.google.com/document/d/19MSl1NSdOlKH9gxs8ZxGOMK7ZuP_ok4J4CZHW5JECRw/edit?usp=sharing>
